services:
 prometheus:
  image: prom/prometheus:latest
  volumes:
   - ./prometheus:/etc/prometheus
   - prom_data:/prometheus
  container_name: prometheus
  ports:
   - 127.0.0.1:9090:9090
  restart: unless-stopped
volumes:
 prom_data:
