services:
 grafana:
  image: grafana/grafana
  container_name: grafana
  restart: unless-stopped
  ports:
   - 127.0.0.1:3000:3000
  volumes:
   - grafana-storage:/var/lib/grafana
  networks:
   - localnet
 volumes:
  grafana-storage: {}

